"""empty message

Revision ID: 706e34da9f84
Revises: 695b8ea2fa78
Create Date: 2022-12-24 15:37:47.183353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '706e34da9f84'
down_revision = '695b8ea2fa78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True, foreign_key='users.id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
